/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.main;

import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.ButtonGroup;
import pos.swing.RoundPanel;

/**
 *
 * @author Anjana
 */
public class Main extends javax.swing.JFrame {

    public static Main mainFrame;
    private ButtonGroup buttonGroup;

    public Main() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        mainFrame = this;

        buttonGroup = new ButtonGroup();
        buttonGroup.add(buttonSellers);
        buttonGroup.add(buttonCategories);
        buttonGroup.add(buttonBills);
        buttonGroup.add(buttonProducts);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new pos.swing.Background();
        panelShadow1 = new pos.swing.PanelShadow();
        profile1 = new pos.includes.Profile();
        buttonSellers = new pos.swing.ButtonMenu();
        buttonCategories = new pos.swing.ButtonMenu();
        buttonBills = new pos.swing.ButtonMenu();
        buttonProducts = new pos.swing.ButtonMenu();
        win_Button1 = new pos.winButtons.Win_Button();
        panelShadow3 = new pos.swing.PanelShadow();
        Sellers = new pos.swing.RoundPanel();
        textField1 = new pos.swing.TextField();
        jLabel1 = new javax.swing.JLabel();
        textField2 = new pos.swing.TextField();
        textField3 = new pos.swing.TextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboBoxSuggestion2 = new pos.combox.ComboBoxSuggestion();
        Bills = new pos.swing.RoundPanel();
        jLabel2 = new javax.swing.JLabel();
        Categories = new pos.swing.RoundPanel();
        jLabel3 = new javax.swing.JLabel();
        Products = new pos.swing.RoundPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelShadow1.setBackground(new java.awt.Color(255, 255, 255));

        buttonSellers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/3.png"))); // NOI18N
        buttonSellers.setText("Sellers");
        buttonSellers.setClickedColor(new java.awt.Color(51, 204, 255));
        buttonSellers.setFocusPainted(false);
        buttonSellers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSellers.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/3.png"))); // NOI18N
        buttonSellers.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        buttonSellers.setUnselectedTextColor(new java.awt.Color(0, 0, 0));
        buttonSellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSellersActionPerformed(evt);
            }
        });

        buttonCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/1.png"))); // NOI18N
        buttonCategories.setText("Categories");
        buttonCategories.setClickedColor(new java.awt.Color(51, 204, 255));
        buttonCategories.setFocusPainted(false);
        buttonCategories.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonCategories.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/1.png"))); // NOI18N
        buttonCategories.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        buttonCategories.setUnselectedTextColor(new java.awt.Color(0, 0, 0));
        buttonCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCategoriesActionPerformed(evt);
            }
        });

        buttonBills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/4.png"))); // NOI18N
        buttonBills.setText("Bills");
        buttonBills.setClickedColor(new java.awt.Color(51, 204, 255));
        buttonBills.setFocusPainted(false);
        buttonBills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBills.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/4.png"))); // NOI18N
        buttonBills.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        buttonBills.setUnselectedTextColor(new java.awt.Color(0, 0, 0));
        buttonBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBillsActionPerformed(evt);
            }
        });

        buttonProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/2.png"))); // NOI18N
        buttonProducts.setText("Products");
        buttonProducts.setClickedColor(new java.awt.Color(51, 204, 255));
        buttonProducts.setFocusPainted(false);
        buttonProducts.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonProducts.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/2.png"))); // NOI18N
        buttonProducts.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        buttonProducts.setUnselectedTextColor(new java.awt.Color(0, 0, 0));
        buttonProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addComponent(buttonSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(buttonCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profile1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBills, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addComponent(profile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buttonBills, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelShadow3.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow3.setLayout(new javax.swing.OverlayLayout(panelShadow3));

        Sellers.setBackground(new java.awt.Color(255, 255, 255));

        textField1.setText("textField1");
        textField1.setShadowColor(new java.awt.Color(23, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 102, 255));
        jLabel1.setText("Manage Sellers");

        textField2.setText("textField1");
        textField2.setShadowColor(new java.awt.Color(23, 102, 255));

        textField3.setText("textField1");
        textField3.setShadowColor(new java.awt.Color(23, 102, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Seller ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Seller ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Seller ID");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Seller ID");

        comboBoxSuggestion2.setPreferredSize(new java.awt.Dimension(151, 34));

        javax.swing.GroupLayout SellersLayout = new javax.swing.GroupLayout(Sellers);
        Sellers.setLayout(SellersLayout);
        SellersLayout.setHorizontalGroup(
            SellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SellersLayout.createSequentialGroup()
                .addGroup(SellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(SellersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addContainerGap(771, Short.MAX_VALUE))
            .addGroup(SellersLayout.createSequentialGroup()
                .addGroup(SellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(textField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(textField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addGroup(SellersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE))
                    .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SellersLayout.setVerticalGroup(
            SellersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SellersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        panelShadow3.add(Sellers);

        Bills.setBackground(new java.awt.Color(242, 246, 253));

        jLabel2.setText("bills");

        javax.swing.GroupLayout BillsLayout = new javax.swing.GroupLayout(Bills);
        Bills.setLayout(BillsLayout);
        BillsLayout.setHorizontalGroup(
            BillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillsLayout.createSequentialGroup()
                .addContainerGap(997, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        BillsLayout.setVerticalGroup(
            BillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BillsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        panelShadow3.add(Bills);

        Categories.setBackground(new java.awt.Color(242, 246, 253));

        jLabel3.setText("Categories");

        javax.swing.GroupLayout CategoriesLayout = new javax.swing.GroupLayout(Categories);
        Categories.setLayout(CategoriesLayout);
        CategoriesLayout.setHorizontalGroup(
            CategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoriesLayout.createSequentialGroup()
                .addContainerGap(962, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        CategoriesLayout.setVerticalGroup(
            CategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CategoriesLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        panelShadow3.add(Categories);

        Products.setBackground(new java.awt.Color(242, 246, 253));

        jLabel4.setText("Products");

        javax.swing.GroupLayout ProductsLayout = new javax.swing.GroupLayout(Products);
        Products.setLayout(ProductsLayout);
        ProductsLayout.setHorizontalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductsLayout.createSequentialGroup()
                .addContainerGap(971, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        ProductsLayout.setVerticalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductsLayout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        panelShadow3.add(Products);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelShadow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(win_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addComponent(win_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(143, 143, 143))
        );

        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProductsActionPerformed

        Products.setVisible(true);
        Sellers.setVisible(false);
        Categories.setVisible(false);
        Bills.setVisible(false);
    }//GEN-LAST:event_buttonProductsActionPerformed

    private void buttonCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCategoriesActionPerformed

        Products.setVisible(false);
        Sellers.setVisible(false);
        Categories.setVisible(true);
        Bills.setVisible(false);
    }//GEN-LAST:event_buttonCategoriesActionPerformed

    private void buttonBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBillsActionPerformed

        Products.setVisible(false);
        Sellers.setVisible(false);
        Categories.setVisible(false);
        Bills.setVisible(true);
    }//GEN-LAST:event_buttonBillsActionPerformed

    private void buttonSellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSellersActionPerformed

        Products.setVisible(false);
        Sellers.setVisible(true);
        Categories.setVisible(false);
        Bills.setVisible(false);
    }//GEN-LAST:event_buttonSellersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pos.swing.RoundPanel Bills;
    private pos.swing.RoundPanel Categories;
    private pos.swing.RoundPanel Products;
    private pos.swing.RoundPanel Sellers;
    private pos.swing.Background background1;
    private pos.swing.ButtonMenu buttonBills;
    private pos.swing.ButtonMenu buttonCategories;
    private pos.swing.ButtonMenu buttonProducts;
    private pos.swing.ButtonMenu buttonSellers;
    private pos.combox.ComboBoxSuggestion comboBoxSuggestion2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private pos.swing.PanelShadow panelShadow1;
    private pos.swing.PanelShadow panelShadow3;
    private pos.includes.Profile profile1;
    private pos.swing.TextField textField1;
    private pos.swing.TextField textField2;
    private pos.swing.TextField textField3;
    private pos.winButtons.Win_Button win_Button1;
    // End of variables declaration//GEN-END:variables
}
