/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.includes;
import Custom.Components.table.TableCustom;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Anjana
 */
public class item extends javax.swing.JPanel {

    /**
     * Creates new form item
     */
    public item() {
        initComponents();
     
         
        loadForm();

    }

    private void loadForm() {
      
     
        
        for(int i=0;i<100;i++){
             Products products1 = new pos.includes.Products();

        jPanel2.add(products1); // Add the form panel
        }
       
             
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new Custom.Components.ScollBar.ScrollPaneWin11();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new java.awt.GridLayout(10, 2, 10, 10));
        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
