/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.SellerUI;
import javax.swing.ImageIcon;
/**
 *
 * @author Anjana
 */
public class Products extends javax.swing.JPanel {

    /**
     * Creates new form Products
     */
    public Products() {
        initComponents();
        labelName.setText("Anjana Ekanayaka");
    }

    public Products(int ProductID, String ProductName, String ProductCategory, double ProductPrice, String ImagePath) {
        initComponents();
        labelName.setText(ProductName);
        labelPrice.setText(Double.toString(ProductPrice));
        labelCategory.setText(ProductCategory);

        ImageIcon imageIcon = new ImageIcon(ImagePath);
        picture.setImage(imageIcon);
        picture.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new Custom.Components.Swing.PanelShadow();
        labelName = new javax.swing.JLabel();
        labelCategory = new javax.swing.JLabel();
        picture = new Custom.Components.Swing.PictureBox();
        textField1 = new Custom.Components.Swing.TextField();
        button1 = new Custom.Components.Swing.Button();
        labelPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 246, 253));
        setMaximumSize(new java.awt.Dimension(190, 319));

        panelShadow1.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow1.setMaximumSize(new java.awt.Dimension(190, 308));

        labelName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Product Name");
        labelName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelCategory.setForeground(new java.awt.Color(0, 102, 0));
        labelCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCategory.setText("Product Category");

        textField1.setShadowColor(new java.awt.Color(51, 0, 255));

        button1.setBackground(new java.awt.Color(0, 204, 255));
        button1.setText("Add to Cart");
        button1.setRippleColor(new java.awt.Color(255, 0, 0));

        labelPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPrice.setForeground(new java.awt.Color(51, 204, 0));
        labelPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrice.setText("150.00");

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(textField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addComponent(labelPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelName)
                .addGap(0, 0, 0)
                .addComponent(labelCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.Components.Swing.Button button1;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPrice;
    private Custom.Components.Swing.PanelShadow panelShadow1;
    private Custom.Components.Swing.PictureBox picture;
    private Custom.Components.Swing.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
