/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pos.Login;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import pos.database.DBConfig;
import pos.SellerUI.SellerUI;
import pos.main.Main;

/**
 *
 * @author Anjana
 */
public class Login extends javax.swing.JFrame {

    Color lineColor = new Color(3, 155, 216);

    public Login() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        labelMessage.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelShadow1 = new Custom.Components.Swing.PanelShadow();
        pictureBox2 = new Custom.Components.Swing.PictureBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textUsername = new Custom.Components.Login.TextField();
        buttonLogin = new Custom.Components.Swing.Button();
        labelMessage = new javax.swing.JLabel();
        textPassword = new Custom.Components.Login.PasswordField();
        buttonExit = new Custom.Components.Swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelShadow1.setBackground(new java.awt.Color(255, 255, 255));
        panelShadow1.setRadius(40);

        pictureBox2.setImage(new javax.swing.ImageIcon(getClass().getResource("/pos/icon/Untitled-1.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        textUsername.setLabelText("Username");
        textUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textUsernameKeyTyped(evt);
            }
        });

        buttonLogin.setBackground(new java.awt.Color(3, 155, 216));
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Login");
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        labelMessage.setForeground(new java.awt.Color(255, 51, 0));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setText("jLabel2");

        textPassword.setLabelText("Password");

        buttonExit.setBackground(new java.awt.Color(255, 51, 51));
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelMessage)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pictureBox2.add(jPanel1);
        jPanel1.setBounds(370, 140, 360, 360);

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pictureBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pictureBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed

        try {

            String username = textUsername.getText().trim();
            char[] passwordChars = textPassword.getPassword();
            String password = new String(passwordChars);

            // Validate inputs
            if (username.isEmpty()) {

                labelMessage.setText("Username Cannot be Empty !");
                textUsername.setLineColor(Color.red);
                textUsername.requestFocusInWindow();
                return;
            }

            if (password.isEmpty()) {
                labelMessage.setText("Password Cannot be Empty !");
                textPassword.setLineColor(Color.red);
                textPassword.requestFocusInWindow();
                return;
            }

            authenticateUser(username, password);

        } catch (Exception e) {

            System.out.println(e);
        }

    }//GEN-LAST:event_buttonLoginActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void textUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textUsernameKeyTyped

        textUsername.setLineColor(lineColor);
        labelMessage.setText("");
    }//GEN-LAST:event_textUsernameKeyTyped

    private void textPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPasswordKeyTyped
        textPassword.setLineColor(lineColor);
        labelMessage.setText("");
    }//GEN-LAST:event_textPasswordKeyTyped

     private void authenticateUser(String username, String password) {

        try {

            DBConfig mycon = new DBConfig();
            Connection con = mycon.connectDB();

            // check if the product with the given ID already exists
            String checkSql = "SELECT COUNT(*),name FROM sellers WHERE id  = ? AND password = ?";
            PreparedStatement checkStatement = con.prepareStatement(checkSql);
            checkStatement.setString(1, username);
            checkStatement.setString(2, password);
            ResultSet resultSet = checkStatement.executeQuery();

            if (resultSet.next() && resultSet.getInt(1) > 0) {
                int userid = Integer.parseInt(username.trim());
                String Name = resultSet.getString("name");
                showSuccessMessage("password Seller correct");
                SellerUI seller = new SellerUI(userid,Name);
                seller.setVisible(true);
                this.setVisible(false);
                

            } else {
                String checkSqlAdmin = "SELECT COUNT(*),name FROM admin WHERE username =? AND password =?";
                PreparedStatement AdmincheckStatement = con.prepareStatement(checkSqlAdmin);
                AdmincheckStatement.setString(1, username);
                AdmincheckStatement.setString(2, password);
                ResultSet AdminresultSet = AdmincheckStatement.executeQuery();

                if (AdminresultSet.next() && AdminresultSet.getInt(1) > 0) {
                    String Name = resultSet.getString("name");
                    showSuccessMessage("password admin correct");
                    Main main = new Main();
                    main.setVisible(true);
                    this.setVisible(false);
                } else {

                    labelMessage.setText("Username or Password Incorrect !");
                    textUsername.setLineColor(Color.red);
                    textUsername.requestFocusInWindow();
                }

            }
            con.close();

        } catch (SQLException e) {
            showErrorMessage(e.toString());

        }
    }
    public void showErrorMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    public void showSuccessMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Custom.Components.Swing.Button buttonExit;
    private Custom.Components.Swing.Button buttonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMessage;
    private Custom.Components.Swing.PanelShadow panelShadow1;
    private Custom.Components.Swing.PictureBox pictureBox2;
    private Custom.Components.Login.PasswordField textPassword;
    private Custom.Components.Login.TextField textUsername;
    // End of variables declaration//GEN-END:variables
}
